language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - hhvm
  - nightly

sudo: false

before_script:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit --coverage-text

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
